apiVersion: v1
kind: Service
metadata:
  name: nginx-webpage
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: NodePort
  ports:
  - nodePort: 31443
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-webpage
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-webpage
  name: nginx-webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-webpage
  strategy: {}
  template:
    metadata:
      labels:
        run: nginx-webpage
    spec:
      containers:
      - image: nginx
        name: nginx-webpage
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: index-html
      volumes:
      - name: index-html
        configMap:
          name: index-html
          items:
          - key: index.html
            path: index.html
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
  labels:
    task: webpage
    k8s-app: webpage
data:
  index.html: |+
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to LUQEL!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <div style="text-align:center;">
    <h1>Welcome to AWS!</h1>
    <p>Coming soon.</p>
    <p>Commit ID:####</p>
    </div >
    </body>
    </html>
---
